apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: "nikhilcluster"
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: "nikhilcluster"
    spec:
      containers:
        - name: "nikhilcluster"
          image: "nikhilbodhe.azurecr.io/nikhilcluster"
          ports:
          - containerPort: 8080